<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search</name>
   <tag></tag>
   <elementGuidId>a412cd34-9510-46f7-bd66-c5047cd9cb40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.fo_btn_search > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://gtn-dev-mysiloam-02.siloamhospitals.com/fo-assets/icons/ic_Search_white@2x.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;container-fluid&quot;]/app-page-patient-data[1]/div[@class=&quot;unprintable d-flex justify-content-start&quot;]/div[@class=&quot;fo_content_container&quot;]/app-widget-patient-data[1]/div[@class=&quot;unprintable&quot;]/form[@class=&quot;ng-dirty ng-valid ng-touched&quot;]/div[@class=&quot;fo_personal_detail_container shadow-4&quot;]/div[@class=&quot;fo_personal_form d-flex justify-content-start&quot;]/div[@class=&quot;form-group fo_personal_form_left&quot;]/div[@class=&quot;form-group d-flex justify-content-between&quot;]/div[@class=&quot;form-pr-bdate&quot;]/div[@class=&quot;input-group&quot;]/button[@class=&quot;fo_btn_search&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://gtn-dev-mysiloam-02.siloamhospitals.com/fo-assets/icons/ic_Search_white@2x.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/img</value>
   </webElementXpaths>
</WebElementEntity>
