<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hapus tanggal appointment list</name>
   <tag></tag>
   <elementGuidId>53ad996a-65e0-4475-96fb-2cd1b3374fc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mydrpicon.icon-mydrpremove</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mydrpicon icon-mydrpremove</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appointment-filter-appointment-list&quot;)/div[@class=&quot;mydrp&quot;]/div[@class=&quot;selectiongroup&quot;]/span[@class=&quot;selbtngroup&quot;]/button[@class=&quot;btnclear btnclearenabled&quot;]/span[@class=&quot;mydrpicon icon-mydrpremove&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//my-date-range-picker[@id='appointment-filter-appointment-list']/div/div/span/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/span</value>
   </webElementXpaths>
</WebElementEntity>
